Сделал ссылку на main.js в index.html и добавил 2 функции в main.js
htmlacademy-javascript/2071141-kekstagram-26 pull request #3
Opened 2022-06-12 18:04 UTC by Peter-Kravchenko

ДЗ 2 модуля

2022-06-12 18:18 UTC, Peter-Kravchenko commented
Немного сбился с ритма, буду догонять

2022-06-14 08:22 UTC, GennadiyM requested changes

2022-06-14 08:22 UTC, GennadiyM commented on js/main.js
> +  min = Math.ceil(min);
перепеши в стрелочную. добавь значение по умолчанию для пвраметра min равное 0

2022-06-14 08:22 UTC, GennadiyM commented on js/main.js
> +function maxStringLength(stringToTest, maxLength) {
у иебя одна фкнкция объявлена как экспрешн, а другая как декларейшен. сделай обе стрелочными. и старайся всегда делать стрелочные

2022-06-14 08:22 UTC, GennadiyM commented on js/main.js
> +const randomInteger = function (min, max) {
название фунеции должно модержать глагол. getRandomInteger

2022-06-14 08:22 UTC, GennadiyM commented on js/main.js
> +function maxStringLength(stringToTest, maxLength) {
название функции должно содердажть глагол getMaxSt...

2022-06-14 08:22 UTC, GennadiyM commented on js/main.js
> +  } else {return false;}
функция всегда что то вернет. условие. просто вернуть результат сравнения return a < b.

2022-06-15 08:24 UTC, GennadiyM approved these changes

2022-06-15 08:24 UTC, merged