Задание больше деталей
htmlacademy-javascript/2071141-kekstagram-26 pull request #4
Opened 2022-06-17 17:04 UTC by Peter-Kravchenko

Выполнил 4 задание

2022-06-19 12:35 UTC, GennadiyM requested changes

2022-06-19 12:35 UTC, GennadiyM commented on js/main.js
> +];
Создай файл mocs и импортируй эти переменные из него

2022-06-19 12:35 UTC, GennadiyM commented on js/main.js
> +/* eslint-disable no-unused-vars */
убери - пусть линтер ругается

2022-06-19 12:35 UTC, GennadiyM commented on js/main.js
>  };
вынеси эти функции в файл utils и импортируй оттуда

2022-06-19 12:35 UTC, GennadiyM commented on js/main.js
> +//console.log (createMultiplePosts);
удали консоли

2022-06-19 12:35 UTC, GennadiyM commented on js/main.js
> +};
избыточно. Достаточно использовать Math.random или библиотеку nanaoid

2022-06-19 12:35 UTC, GennadiyM commented on js/main.js
> +const createMultiplePosts = Array.from({length: MAX_POSTS_COUNT}, createPost);
вот это тоже в mocks вынести

2022-06-19 14:52 UTC, merged

2022-06-20 16:43 UTC, Peter-Kravchenko commented on js/main.js
> +const createMultiplePosts = Array.from({length: MAX_POSTS_COUNT}, createPost);
Точно в mocks, а не в utils? Логичнее поместить в utils, там уже есть функции.