Module5 task1
htmlacademy-javascript/2071141-kekstagram-26 pull request #5
Opened 2022-06-22 16:04 UTC by Peter-Kravchenko

Добавил модули

2022-06-23 17:47 UTC, GennadiyM requested changes

2022-06-23 17:47 UTC, GennadiyM commented on js/mocks.js
> +const createMultiplePosts = Array.from({length: MAX_POSTS_COUNT}, createPost);
const bookings = new Array(MAX_COUNT).fill('').map((_, index) => getBooking(index + 1));
вопспользуйся такой конструкцией. Так ты сможешь передать id карточки и использовать его.

2022-06-23 17:47 UTC, GennadiyM commented on js/mocks.js
> +};
Излишни

2022-06-23 17:47 UTC, GennadiyM commented on js/mocks.js
> +  likes: getRandomPositiveInteger(15, 200),
магические числа - вынести в константы

2022-06-23 17:47 UTC, GennadiyM commented on js/mocks.js
> +  url: `photos/${getRandomPositiveInteger(1,25)}.jpg`,
сюда я подсказал как передать id основанный на индексе элемента в массиве

2022-06-25 22:51 UTC, GennadiyM approved these changes

2022-06-25 22:51 UTC, GennadiyM commented on js/mocks.js
> +const COMMENTS_MIN = 1;
Комментариев может и не быть

2022-06-25 22:51 UTC, GennadiyM commented on js/mocks.js
> +const MIN_LIKES = 15;
Я бы изначально учитывал, что лайков может не быть

2022-06-25 22:51 UTC, GennadiyM commented on js/mocks.js
> +  comments: new Array(getRandomPositiveInteger(COMMENTS_MIN,COMMENTS_MAX)).fill('').map((_,index) => createComment(index + 1)),
У тебя внути одного блока кода два раза index. const createPost = (id) => ({ id, url: `photos/${getRandomPositiveInteger(URL_MIN,URL_MAX)}.jpg`, ... })

2022-06-25 22:51 UTC, GennadiyM commented on js/mocks.js
> +const AVATAR_MAX = 6;
AvatarId {
MIN: 0,
MAX: 6
}
LikeCount {
MIN: 0,
MAX: 25,
}

2022-06-27 11:25 UTC, merged

2022-06-27 16:32 UTC, Peter-Kravchenko commented on js/mocks.js
> +  comments: new Array(getRandomPositiveInteger(COMMENTS_MIN,COMMENTS_MAX)).fill('').map((_,index) => createComment(index + 1)),
А как мне поступить, если мне нужно потом его переназначить для createComment? Я понимаю, что это ошибка, но не могу понять, как от нее уйти.