Module9 task1
htmlacademy-javascript/2071141-kekstagram-26 pull request #8
Opened 2022-07-17 13:09 UTC by Peter-Kravchenko

Масштабирование и фильтры без слайдеров

2022-07-18 08:15 UTC, GennadiyM requested changes

2022-07-18 08:15 UTC, GennadiyM commented on index.html
> +<script src="pristine/pristine.min.js"></script>
type="text/javascript"

2022-07-18 08:15 UTC, GennadiyM commented on index.html
> +<script src="nouislider/nouislider.js"></script>
type="text/javascript"

2022-07-18 08:15 UTC, GennadiyM commented on js/effects.js
> +import { imgUploadPreview } from './scaling.js';
какое-то странное не говорящее за себя название файла. Эффекты. Эффекты чего? Для чего? У чего?

2022-07-18 08:15 UTC, GennadiyM commented on js/effects.js
> +effectsList.addEventListener('click', onFilterChange);
Как должны называться хенделеры событий? on На чем сработал Что сработало. У тебя change сработал?

2022-07-18 08:15 UTC, GennadiyM commented on js/effects.js
> +const onFilterChange = (evt) =>{
=> {

2022-07-18 08:15 UTC, GennadiyM commented on js/effects.js
> +
Не забывай еще два факта: при закрытии попапа надо будет убирать слушателя с фильтров.
При повторном открытии попапа надо будет задавать им значения по умолчанию

2022-07-18 08:15 UTC, GennadiyM commented on js/scaling.js
> +scaleControlValue.value = `${control}`;
а зачем тут это странное превращение в строку?

2022-07-18 08:15 UTC, GennadiyM commented on js/scaling.js
> +  }
Можно упростить логику использую Math.min и Math.max. Если грамотно вложить один в другое - то все получится в одну строку. Попробуй догадаться сам, потом если что покажу ответ

2022-07-18 08:15 UTC, GennadiyM commented on js/scaling.js
> +  scaleControlValue.value = `${control}%`;
а здесь помимо превращения в строку, еще и процент добавился

2022-07-18 08:15 UTC, GennadiyM commented on js/scaling.js
> +  imgUploadPreview.style.transform = `scale(${control / 100})`;
Аналогично предыдущему

2022-07-18 08:15 UTC, GennadiyM commented on js/scaling.js
> +scaleControlDecrease.addEventListener('click', onScaleButtonDecrease);
опять название хендлеров

2022-07-18 08:15 UTC, GennadiyM commented on js/validation.js
>    if (pristine.validate() === false) {
pristine.validate() === false зачем вот это сравнение? оно либо true, либо false. if (!pristine.validate()) {}

2022-07-18 15:09 UTC, Peter-Kravchenko commented on index.html
> +<script src="pristine/pristine.min.js"></script>
Не совсем понял, зачем это?

2022-07-18 15:21 UTC, Peter-Kravchenko commented on js/effects.js
> +import { imgUploadPreview } from './scaling.js';
Я выбрал такое же название, как и класс, который найден при помощи querySelector.

2022-07-19 07:12 UTC, GennadiyM requested changes

2022-07-19 07:12 UTC, GennadiyM commented on js/effects.js
> +import { imgUploadPreview } from './scaling.js';
А как связаны между собой класс и название файла?
Название файла должно отображать содержание файла. 
И вообще в рамках данного проекта можно выделить следующие модули: constants, utils, api (для отправки получения данных), попап с большой фотографией и комментариями, попап редактирования фотографии, ошибка о плохом соединенни, вывод успешного или неуспешного сообщения об отправке.
Нет никакого смысла дробить модуль с редактированием картинки на несколько атомов

2022-07-19 07:12 UTC, GennadiyM commented on js/scaling.js
> +  }
control = Math.min(control + Scale.STEP, Scale.Max)

2022-07-19 07:12 UTC, GennadiyM commented on js/scaling.js
> +  if (control - Scale.STEP > Scale.MIN) {
control = Math.max(control - Scale.STEP, Scale.Min)

2022-07-19 07:12 UTC, GennadiyM commented on js/scaling.js
> +const Scale = {
тоже самое, ты раздробил модуль редактирования фотографии на кучу мелких модулей. И теперь тут тебе будет сложнее следить за обработчиками

2022-07-19 07:12 UTC, GennadiyM commented on js/scaling.js
> +scaleControlDecrease.addEventListener('click', onDownScaleButtonClick);
при закрытии попапа эти обработчики надо будет закрывать

2022-07-19 07:12 UTC, GennadiyM commented on js/scaling.js
> +scaleControlIncrease.addEventListener('click', onUpScaleButtonClick);
попап еще не открыт, а обработчики уже висят

2022-07-20 13:02 UTC, GennadiyM approved these changes

2022-07-20 13:02 UTC, GennadiyM commented on js/effects.js
> +  control = Math.min (control + Scale.STEP, Scale.MAX);
min(

2022-07-20 13:02 UTC, GennadiyM commented on js/effects.js
> +  control = Math.max (control - Scale.STEP, Scale.MIN);
max(

2022-07-20 13:02 UTC, GennadiyM commented on js/effects.js
> +  imagePreview.className = `effects__preview--${evt.target.value}`;
так как ты делегируешь событие я бы проверял на том ли блоке оно сработало. if (evt.target.tag === 'A') { } или if (evt.target.classlist.contains) {}

2022-07-20 13:02 UTC, GennadiyM commented on js/effects.js
> +  scaleControlDecrease.addEventListener('click', onDownScaleButtonClick);
Как называется блок и как называется слушатель

2022-07-20 13:02 UTC, GennadiyM commented on js/effects.js
> +const scaleControlValue = imageScale.querySelector('.scale__control--value');
В одном файле ты дописываешь к ним Element, в этом нет. Выбери общую стратегию и придерживайся ее по всему проекту

2022-07-20 13:03 UTC, merged